services:
  - type: web
    name: django-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: PYTHON_VERSION
        value: 3.11
      # Add other envVars like SECRET_KEY and DEBUG below:
      - key: DJANGO_SECRET_KEY
        value: 4K7dLp9aB8
      - key: DEBUG
        value: False