# Generated by Django 5.1.1 on 2024-09-07 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('qr', models.CharField(max_length=255)),
                ('user', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=100)),
                ('middleName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('companyId', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('confirmation', models.BooleanField(default=False)),
                ('timeIn', models.DateTimeField()),
                ('timeOut', models.DateTimeField()),
                ('checkIn', models.DateTimeField(blank=True, null=True)),
                ('checkOut', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passSlip.user')),
            ],
        ),
    ]
