# Generated by Django 5.1.1 on 2024-09-07 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passSlip', '0002_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slip',
            old_name='confirmation',
            new_name='confHR',
        ),
        migrations.AddField(
            model_name='slip',
            name='confhead',
            field=models.BooleanField(default=False),
        ),
    ]
