# Generated by Django 5.1.1 on 2024-09-08 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passSlip', '0003_rename_confirmation_slip_confhr_slip_confhead'),
    ]

    operations = [
        migrations.AddField(
            model_name='slip',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
