# Generated by Django 5.1.1 on 2024-09-22 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passSlip', '0004_slip_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='slip',
            name='checkInQR',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='slip',
            name='checkOutQR',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
