# Generated by Django 5.1.1 on 2024-09-23 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passSlip', '0006_alter_code_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slip',
            name='checkInQR',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='slip',
            name='checkOutQR',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
