# Generated by Django 5.1.1 on 2024-09-23 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passSlip', '0007_alter_slip_checkinqr_alter_slip_checkoutqr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slip',
            name='confHR',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='slip',
            name='confhead',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
