# Generated by Django 5.1.1 on 2024-09-23 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passSlip', '0008_alter_slip_confhr_alter_slip_confhead'),
    ]

    operations = [
        migrations.AddField(
            model_name='slip',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
