# Generated by Django 5.1.1 on 2024-09-23 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passSlip', '0010_user_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
